### ISSUE TITLE
Bcc Header Not Working

### ISSUE THREAD

**Issue by ArthurZubkoff** [pinceladasdaweb/Ajax-Contact-Form#1]
Hi,

I'm trying to add a checkbox, which allows users to send a copy of their message to themselves. However, I cannot seem to get it working.

Assuming the name field of my checkbox is "```blind-copy```", I included another header in your code:

```
$headers .= "From: $name <$email>" . PHP_EOL;
if (isset($_POST['blind-copy'])) {
    $headers .= "Bcc: $email" . PHP_EOL;
}
$headers .= "Return-Path: $emailTo" . PHP_EOL;
```

**Comment by pinceladasdaweb** [comment]
Try this:

$headers  = 'MIME-Version: 1.1' . PHP_EOL;
$headers .= 'Content-type: text/html; charset=UTF-8' . PHP_EOL;
$headers .= "From: $name <$email>" . PHP_EOL;
$headers .= "Return-Path: $emailTo" . PHP_EOL;
$headers .= "Reply-To: $email" . PHP_EOL;
$headers .= "X-Mailer: PHP/". phpversion() . PHP_EOL;
if (isset($_POST['blind-copy'])) {
    $headers .= "Bcc: $email". PHP_EOL;
}
